### ISSUE TITLE
mahalle geojson

### ISSUE THREAD

**Issue by justinelliotmeyers** [izzetkalic/geojsons-of-turkey#1]
hello,
is there a full mahalle geojson somewhere in this repo?

thanks,
Justin

**Comment by izzetkalic** [comment]
hi, you can download from [this ](https://drive.google.com/drive/folders/1Fd8hz0rI7cVgAK31KXFAIUCujFGoxiyf) link.

**Comment by ikamet** [comment]
Is there a complete list of all the mahalles in Turkey? The estimated total is 55000.
